### PR TITLE
Add table of content

### PR DESCRIPTION
**Pull request by lanlan3322**
Add table of content

### CODE REVIEW

**Comment by lanlan3322** [comment]
Changed to local links.
BTW: pandoc has removed option --latex-engine=xelatex

**Comment by colourful-land** [comment]
> Changed to local links.
> BTW: pandoc has removed option --latex-engine=xelatex

If so, what's the trending method to make Chinese ideographs in the paper not rendered as Tofu?

**Comment by lanlan3322** [comment]
> Thanks lanlan. Often, the table of content is after the foreword. Can you put them behind the "Author's note"?

My system has no chinese support.
Maybe you try to use --pdf-engine=xelatex

**Comment by colourful-land** [comment]
Thanks! This solves issue #63 

In a separate commit, I'll add some comment for those whose pandoc doesn't accept xelatex.

**Pull request merged**
