### PR TITLE
adds a view for the xdai action

### PR DESCRIPTION
**Pull request by James-Sangalli**
For #176

### CODE REVIEW

**Comment by JamesSmartCell** [comment]
Is the <name> tag inconsistent with schema? In all other tokenscript the action name is defined similar to this:

`<ts:name>`
`        <ts:string xml:lang="en">Enter</ts:string>`
`        <ts:string xml:lang="zh">入場</ts:string>`
`        <ts:string xml:lang="es">Entrar</ts:string>`
`</ts:name>`

Whereas here it's:

`<ts:name>Transfer xDAI to DAI</ts:name>`

**Comment by JamesSmartCell** [comment]
Also shouldn't the `<style>` be filled in or are we assuming that adding the style as a reference is all that's needed and we should assume that a .css specified in the include section is automagically inserted as style? That doesn't seem very 'tokenscripty'. 

Like this:

`</ts:transaction>`
`    <style>`
`    body {`
`    font-family: Arial;`
`}`
...
`</style>`

**Comment by colourful-land** [comment]
> Is the `<name>` tag inconsistent with schema? In all other tokenscript the action name is defined similar to this:

@JamesSmartCell Solved in https://github.com/AlphaWallet/TokenScript/pull/178

**Comment by colourful-land** [comment]
> Also shouldn't the `<style>` be filled in or are we assuming that adding the style as a reference is all that's needed and we should assume that a .css specified in the include section is automagically inserted as style? That doesn't seem very 'tokenscripty'.

Solved with a new commit to this issue.

**Comment by James-Sangalli** [comment]
@JamesSmartCell @colourful-land your enquires have been addressed.

**Comment by colourful-land** [comment]
> @JamesSmartCell @colourful-land your enquires have been addressed.

My request: you touched  `examples/erc20/dai-bridge.en.shtml` - you shouldn't.

Your way to "address it": added even more changes to `examples/erc20/dai-bridge.en.shtml`

**Comment by colourful-land** [comment]
@James-Sangalli please handle the conflict

**Pull request merged**
