### PR TITLE
AdmissionTicket -> EntryToken for clarity in tutorial

### PR DESCRIPTION
**Pull request by James-Sangalli**
Let's not merge this yet until we can be sure the .tsml file is running properly on iOS and Android and we are satisfied with the content.

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli 

1. Maybe a good time to rename the `ticket/` directory to `entry/`/`entryToken`/`entry-token`?

2. For several of the attributes whose values are not based on bitmasks (e.g. `locality`), we now have:

```
<ts:origin contract="erc875">
```

instead of:

```
<tb:origin contract="holding-contract">
```

The latter was used in the [spawnable MeetupContract.xml](https://github.com/AlphaWallet/contracts/blob/master/spawnable-contract/schema1/MeetupContract.xml).

I think it should be the latter, but @colourful-land, do we have a definition of what "holding-contract" actually means and what should be the correct value for `contract` here and what are the possible values?

3. The encoding of the `time` attribute seems incorrect:

token ID: `0x474d542b33000000000000000000000001075b2282f05255534b534101050001` (and `0x...2`)
Bitmask for `time`: `0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000`
So the value is `0x542b33000000000000000000000001075b2282`

We should expect every byte sequence eg. `0x54`, `0x2b` to be mapped into a character like "1", "9" respectively (assuming the desired GeneralizedTime is `19970421160340+0000`). But `0x54` and `0x2b` are `T` and `{` respectively.

I think it was broken too for the MeetupContract which we deployed a few months ago.

**Comment by colourful-land** [comment]
> do we have a definition of what "holding-contract" actually means and what should be the correct value for contract here and what are the possible values?

@hboon For now, Sangalli can keep his version. The contract id concept was dropped in 2019/04 schema because it turned out to be more complicated than originally thought back in 2018. Reasons being.

1. Contracts participating only 1 or more actions, but not all actions, actually exist, therefore enriching the contract addresses that have to be mentioned at the beginning of the file.

2. Unlike attributes, we are not using contracts for value (we are using attributes that source data from contracts for value), therefore I am inclined to use `label=` for `<contract>` to avoid namespace competition with attributes.

Both are considerable changes that would break the current schema, so it can't be done with 2019/04. The contract labelling will return in 2019/05, by which time we can update the example to:

    <contract interface="erc875" label="erc875">

So that Sangalli's existing code doesn't break.

**Comment by hboon** [comment]
```
<contract interface="erc875" label="erc875">
```

I haven't noticed this ^. But it's good to know.

@colourful-land I was referring to this:

> 2. For several of the attributes whose values are not based on bitmasks (e.g. `locality`), we now have:

```
<ts:origin contract="erc875">
```

> instead of:

```
<tb:origin contract="holding-contract">
```

> The latter was used in the [spawnable MeetupContract.xml](https://github.com/AlphaWallet/contracts/blob/master/spawnable-contract/schema1/MeetupContract.xml).

**Comment by colourful-land** [comment]
Can you rebase on the `dai+schema-2019/05` branch? By the time it is merged, yours is ready to go in with the new schema.

**Pull request merged**
