### PR TITLE
RFC4912 required a <type> for a named type that defines a type

### PR DESCRIPTION
**Pull request by colourful-land**
1. merge this together with https://github.com/AlphaWallet/TokenScript-Examples/pull/93

2. Don't merge this in until both αW can handle the new schema.

### CODE REVIEW

**Comment by colourful-land** [comment]
> @colourful-land should this require a new schema version since `2020/06` has already been shipped?

I was hoping to sneak that in since we can't do a new schema version until 2021. The αW can be written to handle both cases (`<type>` clearly defined or missing out)

**Comment by hboon** [comment]
> > @colourful-land should this require a new schema version since `2020/06` has already been shipped?
> 
> I was hoping to sneak that in since we can't do a new schema version until 2021. The αW can be written to handle both cases (`<type>` clearly defined or missing out). If you use xpath it should be easy to include the case with `<type>` or not

We can do that in an updated app version. But the older versions in the install base will pick up the updated TokenScript files that includes this change like this [1] and break.

[1] https://github.com/AlphaWallet/TokenScript-Examples/pull/93/files

**Comment by colourful-land** [comment]
@hboon exactly. How about we make αW android/ios both compatible with both format and wait a few weeks to see how many users upgraded before updating the Repo server?

**Comment by hboon** [comment]
@colourful-land I don't mind either way. You and @James-Sangalli decide then :)

**Comment by colourful-land** [comment]
>     2\. Don't merge this in until both αW can handle the new schema.

We are getting there. It's been 3 days and the 3.0.5 user base has just surpassed the 3.0.2 user base. I hope by the end of this week we can merge this in already.

Screenshot_2020-07-09 Estadísticas - AlphaWallet - Google Play Console

**Comment by colourful-land** [comment]
Usage of the Android version that didn't support `<type>` dropped to 15% (iOS should have fallen below this many days ago), so merging this in. I used merge instead of squash because this branch has a fork that is in PR to be merged soon

**Pull request merged**
