### PR TITLE
Added Kudos TokenScript

### PR DESCRIPTION
**Pull request by edsonayllon**
For [this bounty](https://berlin.bounties.network/bounty/3257).
- [Token Address](https://etherscan.io/token/0x2aea4add166ebf38b63d09a75de1a7b94aa24163)
- [Kudos Solidity file](https://github.com/gitcoinco/Kudos721Contract/blob/master/contracts/Kudos.sol)
- [Kudos Token Used](https://gitcoin.co/kudos/2576/junior_release_manager)

63068138-1b363580-bee0-11e9-92aa-ad18d9d58ca1
63068137-1b363580-bee0-11e9-97fd-fcbb67c463d8

### CODE REVIEW

**Comment by James-Sangalli** [comment]
Congrats @edsonayllon you won the bounty!

**Comment by edsonayllon** [comment]
Great, will do soon. I'll reach out if questions come up tomorrow.

**Comment by James-Sangalli** [comment]
@edsonayllon don't forget to tweet your experience writing a tokenscript :)

**Comment by zhangzhongnan928** [comment]
@James-Sangalli   Once done, please make an announcement.

**Pull request closed without merging**
