### PR TITLE
UEFA new layout shtml

### PR DESCRIPTION
**Pull request by developerpeachy**
- Done simple html/css layout 
- Tested on another iPhone, need to test on Android

### CODE REVIEW

**Comment by James-Sangalli** [comment]
IMG_1385
@developerpeachy possible to fix this?

**Comment by developerpeachy** [comment]
hey james, what phone is this running on and how can i get two cards showing on my build to test and fix

**Comment by developerpeachy** [comment]
Suggestion: can we remove unnecessary margins in webview? is this possible?

**Comment by hboon** [comment]
> Suggestion: can we remove unnecessary margins in webview? is this possible?

@developerpeachy @James-Sangalli Fixed with https://github.com/AlphaWallet/alpha-wallet-ios/pull/1596

**Comment by James-Sangalli** [comment]
> IMG_1385
> @developerpeachy possible to fix this?

Solved here: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1596

**Comment by James-Sangalli** [comment]
Added https://github.com/AlphaWallet/TokenScript/issues/284 for the redeem section, please pull from master and make a new PR and branch for this change

**Comment by James-Sangalli** [comment]
Closes https://github.com/AlphaWallet/TokenScript/issues/286 @developerpeachy remember to reference relevant issues

**Pull request merged**
