### PR TITLE
adding a donation address

### PR DESCRIPTION
**Pull request by colourful-land**
@James-Sangalli please verify that the public key I provided corresponds to the donation address I provided. If it matches, please update the donation address on README on the top level and approve/merge this.

### CODE REVIEW

**Comment by colourful-land** [comment]
> Result is 0x5052Ff54432D9f046816dBD0ea987da4B4F547a1

Your code looks correct, so the tool I used to generate vanity key is bad.

````
$ time target/release/ethaddrgen -e '^0000.*0000$'
---------------------------------------------------------------------------------------
Found address: 0x00001d9a7b899f7cec9ab31e52c4fffefff70000
Generated private key: b81748e972e0112ac9ace985f260390a26ea100a25f7a563d2b0a39465de5a03
Import this private key into an ethereum wallet in order to use the address.
Buy me a cup of coffee; my ethereum address: 0xc0ffee3bd37d408910ecab316a07269fc49a20ee
---------------------------------------------------------------------------------------

real	110m20.978s
user	861m51.541s
sys	6m9.888s
````

So the above private key given by the output leads to a different key than the 'found address'.

I guess I'll have to resort to JavaScript based vanity address generation tool. I chose a tool written in a compiled (not interpreted) language for speed, but it seems it's vanity to try to use a fast tool.

**Comment by colourful-land** [comment]
Can I ask you to generate an address instead? Note that we must provide the public key explicitly because Peter Liu will not be able to derive it from the address. Kindly update the document once you are done.

**Comment by colourful-land** [comment]
@James-Sangalli can yo do something about it?

**Comment by James-Sangalli** [comment]
@colourful-land have the private key to this: 

0xdeadd42a3ab7d14626a98eadebd26ae8c81b07e4

pub: f0985bd9dbb6f461adc994a0c12595716a7f4fb2879bfc5155dffec3770096201c13f8314b46db8d8177887f8d95af1f2dd217291ce6ffe9183681186696bbe5

**Comment by colourful-land** [comment]
> @colourful-land have the private key to this:
> 
> 0xdeadd42a3ab7d14626a98eadebd26ae8c81b07e4
> 
> pub: f0985bd9dbb6f461adc994a0c12595716a7f4fb2879bfc5155dffec3770096201c13f8314b46db8d8177887f8d95af1f2dd217291ce6ffe9183681186696bbe5

Read the request:

> @James-Sangalli please verify that the public key I provided corresponds to the donation address I provided. If it matches, *please update the donation address on README on the top level*

And also update the public key to it in the security.md

**Pull request merged**
