### PR TITLE
Inputs >data

### LINKED ISSUE #133: transaction value and "to"
Many solidity functions allow you to add ether if the function call is 'payable', we need this feature also.

### PR DESCRIPTION
**Pull request by colourful-land**
resolves #133 and replaces `<inputs>` with `<data>`.

### CODE REVIEW

**Comment by hboon** [comment]
I’m on mobile. Is the right branch? Seems to be the branch for #152.

**Comment by colourful-land** [comment]
> I’m on mobile. Is the right branch? Seems to be the branch for #152.

I based this branch on the branch for #152 (confident that it will be merged) to avoid merge conflict.

**Comment by colourful-land** [comment]
> I’m on mobile. Is the right branch? Seems to be the branch for #152.

After #152 is merged, the "Files Changed" tab of github automatically updated to show the difference between this branch to the new master only, not including all commits since the diverge, shortened from the previous changeset by more than 50%. Good job github.

**Comment by hboon** [comment]
inputs -> data looks clear, but do we need to support #133 with version 2019/05?

**Comment by colourful-land** [comment]
> inputs -> data looks clear, but do we need to support #133 with version 2019/05?

Yes, since it's needed for x-dai bridge.

**Comment by hboon** [comment]
> > inputs -> data looks clear, but do we need to support #133 with version 2019/05?
> 
> Yes, since it's needed for x-dai bridge.

Ok.

**Comment by hboon** [comment]
@colourful-land `git rebase master` is useful here. See https://github.com/AlphaWallet/TokenScript/wiki/Useful-Git-Commands#rebase-master

**Comment by JamesSmartCell** [comment]
Should those schema changes be in this PR alongside the smaller schema changes? Or is it just the inputs -> data changes I'm looking at?

**Pull request merged**
