### PR TITLE
Fix: TokenScript file for ERC20's ownerApproved filter

### PR DESCRIPTION
**Pull request by hboon**
Also assumes #361 is correct.

### CODE REVIEW

**Comment by hboon** [comment]
Hang on. Forgot to pull latest.

**Comment by hboon** [comment]
Good for review

**Comment by James-Sangalli** [comment]
> Good for review

Haha, the other PR wasn't merged so you might wanna rebase with master again

**Comment by hboon** [comment]
> Haha, the other PR wasn't merged so you might wanna rebase with master again

@James-Sangalli done

**Pull request merged**
