### PR TITLE
Schema/2020/03

### PR DESCRIPTION
**Pull request by colourful-land**
Implemented: https://community.tokenscript.org/t/weekly-design-meeting-21/329

Unimplemented: the use of RDN to identify token and the use of `disctinct` attributes (forming RDN) instead of using `<origin>` for token. - We talked about that in the weekly meeting but that change is significant and we push it to the next version of the schema.

### CODE REVIEW

**Comment by hboon** [comment]
> @colourful-land changing view-iconified to item-view

@colourful-land what about `<row-view>` or `<collapsed-view>` or `<mini-view>` instead? I'm not attached to them, but feels like "item" (or "instance") doesn't have much meaning either.

**Comment by James-Sangalli** [comment]
> > @colourful-land changing view-iconified to item-view
> 
> @colourful-land what about `<row-view>` or `<collapsed-view>` or `<mini-view>` instead? I'm not attached to them, but feels like "item" (or "instance") doesn't have much meaning either.

@tomekalphawallet

**Comment by colourful-land** [comment]
> > @colourful-land changing view-iconified to item-view
> 
> @colourful-land what about `<row-view>` or `<collapsed-view>` or `<mini-view>` instead? I'm not attached to them, but feels like "item" (or "instance") doesn't have much meaning either.

None of them suggests the items are selectable and multi-selectable. Imagine click and hold a mini-view. Previously the word "iconified" was chosen so the developers feel that they are selectable, but that was 'lost in translation'. Naming it '<selectable-view>' is, on the other hand, overdoing it.

On top of that,  `<row-view>` and  `<mini-view>` hint its presentation, therefore when presentation changes they must, too (e.g. when they are used as a button). You can argue `iconified` has the same problem (the word `iconified` was chosen not for that reason, but to hint it is used like a file-manage icon, which apparently failed). 

`<collapsed-view>` works best for an item-view that is a button which opens a collection of NFT. Not so portable to currency tokens.

P.S. Why I don't remember having discussed this on the weekly meeting but only with @jzaki and @tomekalphawallet - I might have thought it was discussed with you guys already.

**Comment by colourful-land** [comment]
The last commit resolves https://github.com/AlphaWallet/TokenScript-Examples/issues/29

**Comment by James-Sangalli** [comment]
17e8a06 deployed

**Comment by James-Sangalli** [comment]
deployed a5389a0

**Pull request merged**
